USE ProgrammerService

CREATE TABLE Roles
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL 
)

CREATE TABLE Permission
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(50) NOT NULL
)

CREATE TABLE Roles_Permissions
(
	Id INT PRIMARY KEY IDENTITY,
	Role_id INT NOT NULL,
	Permission_id INT NOT NULL
	FOREIGN KEY (Role_id) REFERENCES Roles(Id) ON DELETE CASCADE,
	FOREIGN KEY (Permission_id) REFERENCES Permission(Id) ON DELETE CASCADE
)

CREATE TABLE Accounts
(
	Id INT PRIMARY KEY IDENTITY,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Password VARCHAR(30) NOT NULL,
	Role_id INT NOT NULL 
	FOREIGN KEY (Role_id) REFERENCES Roles(Id) ON DELETE CASCADE
)

CREATE TABLE Visitors
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(200) NOT NULL,
	Nickname VARCHAR(20) NOT NULL UNIQUE,
	Date_of_birth DATE NOT NULL,
	Account_id INT NOT NULL
	FOREIGN KEY (Account_id) REFERENCES Accounts(Id) ON DELETE CASCADE
)

CREATE TABLE Programmers
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(200) NOT NULL,
	Alias VARCHAR(100) NULL,
	Date_of_birth DATE NOT NULL,
	Account_id INT NOT NULL
)

CREATE TABLE Groups
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL,
	Founding_date DATE NOT NULL,
	Number_of_programmer INT NOT NULL,
	Account_id INT NOT NULL
)

CREATE TABLE Related_accounts
(
	Id INT PRIMARY KEY IDENTITY,
	Account_id INT NOT NULL UNIQUE,
	Programmer_id INT UNIQUE, 
	Group_id INT UNIQUE,
	FOREIGN KEY (Programmer_id) REFERENCES Programmers(Id) ON DELETE CASCADE,
	FOREIGN KEY (Group_id) REFERENCES Groups(Id) ON DELETE CASCADE,
	FOREIGN KEY (Account_id) REFERENCES Accounts(Id) ON DELETE CASCADE,
)

CREATE TABLE Programms
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL,
	Date_of_writing DATE NOT NULL
)

CREATE TABLE Seriess
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL,
	Date_of_writing DATE NOT NULL
)

CREATE TABLE Genres
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL
)

CREATE TABLE Sertifications
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL,
	Number_of_sales INT NOT NULL CHECK(Number_of_sales >= 0)
)

CREATE TABLE Logs
(
	Id INT PRIMARY KEY IDENTITY,
	Entity_Id INT NOT NULL,
	Representation VARCHAR(255) NOT NULL,
	Date_of_create DATE NOT NULL DEFAULT GETDATE()
)

CREATE TABLE Programmers_Programms
(
	Id INT PRIMARY KEY IDENTITY,
	Programmer_id INT NOT NULL,
	Programm_id INT NULL,
	FOREIGN KEY (Programmer_id) REFERENCES Programmers(Id) ON DELETE CASCADE,
	FOREIGN KEY (Programm_id) REFERENCES Programms(Id) ON DELETE CASCADE
)

CREATE TABLE Groups_Programms
(
	Id INT PRIMARY KEY IDENTITY,
	Group_id INT NOT NULL,
	Programm_id INT NULL,
	FOREIGN KEY (Group_id) REFERENCES Groups(Id) ON DELETE CASCADE,
	FOREIGN KEY (Programm_id) REFERENCES Programms(Id) ON DELETE CASCADE
)

CREATE TABLE Seriess_Genres
(
	Id INT PRIMARY KEY IDENTITY,
	Series_id INT NOT NULL,
	Genre_id INT NOT NULL,
	FOREIGN KEY (Series_id) REFERENCES Seriess(Id) ON DELETE CASCADE,
	FOREIGN KEY (Genre_id) REFERENCES Genres(Id) ON DELETE CASCADE
)

CREATE TABLE Programms_Genres
(
	Id INT PRIMARY KEY IDENTITY,
	Programm_id INT NOT NULL,
	Genre_id INT NOT NULL,
	FOREIGN KEY (Programm_id) REFERENCES Programms(Id) ON DELETE CASCADE,
	FOREIGN KEY (Genre_id) REFERENCES Genres(Id) ON DELETE CASCADE
)

CREATE TABLE Programmers_Seriess
(
	Id INT PRIMARY KEY IDENTITY,
	Programmer_id INT NOT NULL,
	Series_id INT NULL,
	FOREIGN KEY (Programmer_id) REFERENCES Programmers(Id) ON DELETE CASCADE,
	FOREIGN KEY (Series_id) REFERENCES Seriess(Id) ON DELETE CASCADE
)

CREATE TABLE Groups_Seriess
(
	Id INT PRIMARY KEY IDENTITY,
	Group_id INT NOT NULL,
	Series_id INT NULL,
	FOREIGN KEY (Group_id) REFERENCES Groups(Id) ON DELETE CASCADE,
	FOREIGN KEY (Series_id) REFERENCES Seriess(Id) ON DELETE CASCADE
)

CREATE TABLE Groups_Programmers
(
	Id INT PRIMARY KEY IDENTITY,
	Group_id INT NOT NULL,
	Programmer_id INT NOT NULL,
	FOREIGN KEY (Group_id) REFERENCES Groups(Id) ON DELETE CASCADE,
	FOREIGN KEY (Programmer_id) REFERENCES Programmers(Id) ON DELETE CASCADE
)

CREATE TABLE Seriess_Sertifications
(
	Id INT PRIMARY KEY IDENTITY,
	Series_id INT NOT NULL,
	Sertification_id INT NULL,
	FOREIGN KEY (Series_id) REFERENCES Seriess(Id) ON DELETE CASCADE,
	FOREIGN KEY (Sertification_id) REFERENCES Sertifications(Id) ON DELETE CASCADE
)

CREATE TABLE Programms_Sertifications
(
	Id INT PRIMARY KEY IDENTITY,
	Programm_id INT NOT NULL,
	Sertification_id INT NULL,
	FOREIGN KEY (Programm_id) REFERENCES Programms(Id) ON DELETE CASCADE,
	FOREIGN KEY (Sertification_id) REFERENCES Sertifications(Id) ON DELETE CASCADE
)